-- ═════════════════════════════════════════════════════════════════════════════
-- DEPRECATED — do not run this file.
-- ═════════════════════════════════════════════════════════════════════════════
-- The SAWA database is now defined by the ordered, idempotent migrations in
--   supabase/migrations/
-- See supabase/README.md for how to apply and verify them.
--
-- The previous contents of this file (v1 contact_requests schema + the
-- abandoned "platform redesign" tables) included the policy
--   "authenticated_read_only" … using (true)
-- which let ANY signed-in user read every contact request. Re-running it
-- would re-open that hole. It remains available in git history only.
-- ═════════════════════════════════════════════════════════════════════════════
select 'supabase/schema.sql is deprecated — apply supabase/migrations/* instead (see supabase/README.md).' as notice;
