-- ═════════════════════════════════════════════════════════════════════════════
-- SAWA v2 — Migration 400: RPC functions (the v2 app's write API)
-- ═════════════════════════════════════════════════════════════════════════════
-- SECURITY DEFINER functions with an empty search_path. They never trust the
-- caller for identity: customer_id always comes from auth.uid() (enforced by
-- the insert triggers, which also run inside these functions).
-- ═════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- submit_contact_request — guest or signed-in customer → a published provider.
-- Returns the reference so the guest gets a real confirmation without any
-- read access to the table.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.submit_contact_request(
  p_provider_id uuid,
  p_name        text,
  p_contact     text,
  p_message     text   default null,
  p_inquiry_id  bigint default null,
  p_service_id  uuid   default null
)
returns table (reference_code text, created_at timestamptz)
language plpgsql
volatile
security definer
set search_path = ''
as $$
#variable_conflict use_column
begin
  if p_provider_id is null then
    raise exception 'provider_required' using errcode = '22023';
  end if;

  return query
  insert into public.contact_requests as cr
    (provider_id, provider_uuid, user_name, user_contact, note, inquiry_id, service_id)
  values
    (p_provider_id::text, p_provider_id, p_name, p_contact, p_message, p_inquiry_id, p_service_id)
  returning cr.reference_code, cr.created_at;
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- create_event_inquiry — planner submission (guest needs a contact number).
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.create_event_inquiry(
  p_event_type    text,
  p_guest_count   int           default null,
  p_city          text          default null,
  p_area          text          default null,
  p_event_date    date          default null,
  p_budget_min    numeric       default null,
  p_budget_max    numeric       default null,
  p_currency      text          default 'IQD',
  p_services      text[]        default '{}',
  p_style         text          default null,
  p_notes         text          default null,
  p_guest_name    text          default null,
  p_guest_contact text          default null
)
returns table (id bigint, reference_code text, created_at timestamptz)
language plpgsql
volatile
security definer
set search_path = ''
as $$
#variable_conflict use_column
begin
  return query
  insert into public.event_inquiries as ei
    (event_type, guest_count, city, area, event_date, budget_min, budget_max,
     currency, services, style, notes, guest_name, guest_contact, reference_code)
  values
    (p_event_type, p_guest_count, p_city, p_area, p_event_date, p_budget_min, p_budget_max,
     coalesce(p_currency, 'IQD'), coalesce(p_services, '{}'), p_style, p_notes,
     p_guest_name, p_guest_contact, null)   -- reference_code is generated by the trigger
  returning ei.id, ei.reference_code, ei.created_at;
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- record_provider_view — real profile-view events, de-duplicated per viewer
-- (account or hashed network) for 30 minutes. Owners viewing themselves are
-- not counted.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.record_provider_view(p_provider_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_uid  uuid := auth.uid();
  v_hash text := sawa_private.request_ip_hash();
begin
  if not exists (select 1 from public.providers where id = p_provider_id and status = 'published') then
    return;
  end if;
  if v_uid is not null and exists (select 1 from public.providers where id = p_provider_id and user_id = v_uid) then
    return;
  end if;
  if exists (
       select 1 from public.provider_profile_views v
        where v.provider_id = p_provider_id
          and v.viewed_at > now() - interval '30 minutes'
          and (   (v_uid is not null and v.viewer_id = v_uid)
               or (v_uid is null and v_hash is not null and v.viewer_id is null and v.viewer_hash = v_hash))) then
    return;
  end if;

  insert into public.provider_profile_views (provider_id, viewer_id, viewer_hash)
  values (p_provider_id, v_uid, v_hash);
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- get_provider_stats — dashboard numbers computed from real rows only.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.get_provider_stats(p_provider_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not (public.owns_provider(p_provider_id) or public.is_admin()) then
    raise exception 'not_allowed' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'status',             (select status from public.providers where id = p_provider_id),
    'views_total',        (select count(*) from public.provider_profile_views where provider_id = p_provider_id),
    'views_last_30_days', (select count(*) from public.provider_profile_views
                            where provider_id = p_provider_id and viewed_at > now() - interval '30 days'),
    'requests_total',     (select count(*) from public.contact_requests
                            where provider_uuid = p_provider_id and forwarded_to_provider_at is not null),
    'requests_new',       (select count(*) from public.contact_requests
                            where provider_uuid = p_provider_id and forwarded_to_provider_at is not null
                              and status = 'new'),
    'services_active',    (select count(*) from public.services where provider_id = p_provider_id and is_active),
    'services_total',     (select count(*) from public.services where provider_id = p_provider_id)
  );
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Grants
-- ─────────────────────────────────────────────────────────────────────────────
revoke all on function public.submit_contact_request(uuid, text, text, text, bigint, uuid) from public;
revoke all on function public.create_event_inquiry(text, int, text, text, date, numeric, numeric, text, text[], text, text, text, text) from public;
revoke all on function public.record_provider_view(uuid) from public;
revoke all on function public.get_provider_stats(uuid) from public;

grant execute on function public.submit_contact_request(uuid, text, text, text, bigint, uuid) to anon, authenticated;
grant execute on function public.create_event_inquiry(text, int, text, text, date, numeric, numeric, text, text[], text, text, text, text) to anon, authenticated;
grant execute on function public.record_provider_view(uuid) to anon, authenticated;
grant execute on function public.get_provider_stats(uuid) to authenticated;

-- Policy helpers must stay callable by API roles (they only reveal facts
-- about the caller or about public rows).
grant execute on function public.is_admin()                  to anon, authenticated;
grant execute on function public.current_app_role()          to anon, authenticated;
grant execute on function public.owns_provider(uuid)         to anon, authenticated;
grant execute on function public.is_public_provider(uuid)    to anon, authenticated;
